spring.application.name=currency_exchanger

# Server configuration
server.port=${SERVER_PORT}

# JWT Token
jwt.token.expiration = 3600000
jwt.secret = ${JWT_SECRET}

# Databse connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Database configuration
spring.jpa.hibernate.ddl-auto=update